# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9da7f2ad515f0f38a338274fb46d2dbfb773a8f8ed5ca8d8350bf85a6e7638ebe25457acaa4471c9d0f4edbb277cd70cdc898cfb2e05200b15d6643004dcb86b

test:
  secret_key_base: ec309b2d457a7244dc53e756444864aeec2d1295f47225b36d950d7821ad58d2688f517a519301d1d15e46df0355bbf602b844e0f705fb1e9b7aafec94685eea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
